### ISSUE TITLE
Functionality change: clicking on cards on the dashboard shouldn't take you to a new page

### ISSUE THREAD

**Issue by pjames27** [codexstanford/codex-insurance-fullstack#4]
When on the Dashboard page, clicking on a card for a policy or a person currently takes you to the page for Policies or People, respectively, then opens the modal. Instead, it should keep you on the Dashboard and open the applicable modal.

**Comment by pfw13** [comment]
I think it should because of UX. Changing the view in the app should be reflected in the URL so that you use browser history (i.e., navigating back and forward) or sending/saving the URL and using it to navigate to the exact same view in the app. If we would do that for both, creating, e.g., a claim in the dasbhoard and at the "Claims" page, we would have two different URLs which do (remotely) the exact same thing. I think this duplication should be avoided.

**Comment by pfw13** [comment]
@pjames27, have we decided how we should proceed here?

**Comment by pjames27** [comment]
I still think it shouldn't take us to a new page, but I'm receptive to what you were saying about routing taking users to the same view of the app. This would lead to some redundant code, but I think that's a worthwhile tradeoff for the UX here.
Let me run this by the group during today's meeting.

**Comment by pjames27** [comment]
It turns out asking this question opens a whole other can of worms about general dashboard functionality. Since this isn't relevant while we're only doing Cardinal Care, we're entirely deferring this for the time being.
As a result, for now, the dashboard will only contain claims, and the other objects won't have their own dedicated pages.
